#!/usr/bin/env python3
"""Builds CODEMAP.md: one line per source file, taken from the first lines of its own header comment, so the map
can never drift from the code. Run with --check to fail if the file on disk is out of date (used by scripts/check.sh)."""
import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "CODEMAP.md"

def first_sentence(path):
    """The first sentence of a file's header comment (//! for Rust, a leading docstring or # comment for scripts)."""
    text = path.read_text(errors="ignore").splitlines()
    lines = []
    for l in text[:12]:
        m = re.match(r"\s*//!\s?(.*)", l)
        if m is None:
            m = re.match(r"\s*#\s?(.*)", l) if l.startswith("#") and not l.startswith("#!") else None
        if m is None:
            if lines:
                break
            continue
        lines.append(m.group(1))
        if lines and lines[-1].rstrip().endswith("."):
            break
    s = " ".join(x.strip() for x in lines).strip()
    return (re.split(r"(?<=[.])\s", s)[0] if s else "(no header comment)").replace("|", "/")

def section(title, files):
    rows = "\n".join(f"| `{f.relative_to(ROOT)}` | {first_sentence(f)} |" for f in files)
    return f"## {title}\n\n| File | What it is |\n|---|---|\n{rows}\n"

def build():
    src = sorted((ROOT / "src").rglob("*.rs"))
    groups = {}
    for f in src:
        rel = f.relative_to(ROOT / "src")
        key = rel.parts[0] if len(rel.parts) > 1 else "(crate root)"
        groups.setdefault(key, []).append(f)
    parts = ["# Code map\n\nGenerated by `scripts/codemap.py` from each file's own header comment. Do not edit by hand: change the header "
             "comment in the file, then run `scripts/check.sh --fix`.\n\nRun `scripts/check.sh` before and after changing anything; it tests every module and checks that every feature is alive.\n"]
    for key in sorted(groups, key=lambda k: (k.startswith("("), k)):
        parts.append(section(f"src/{key}" if not key.startswith("(") else "src (crate root)", groups[key]))
    parts.append(section("tests", sorted((ROOT / "tests").glob("*.rs"))))
    parts.append(section("examples", sorted((ROOT / "examples").glob("*.rs"))))
    parts.append(section("scripts", sorted(p for p in (ROOT / "scripts").rglob("*") if p.suffix in (".py", ".sh") and p.name != "codemap.py")))
    return "\n".join(parts)

if __name__ == "__main__":
    new = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != new:
            sys.exit("CODEMAP.md is out of date. Run: scripts/check.sh --fix")
        print("code map up to date")
    else:
        OUT.write_text(new)
        print(f"wrote {OUT.relative_to(ROOT)}")
